// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYKlxh-8iMxMcXnCvMW87SjVB1DCQlaTk',
    appId: '1:608987467181:web:1393cbcdfba2248a7c6524',
    messagingSenderId: '608987467181',
    projectId: 'finalyearproject-b9f5a',
    authDomain: 'finalyearproject-b9f5a.firebaseapp.com',
    storageBucket: 'finalyearproject-b9f5a.appspot.com',
    measurementId: 'G-GTT3FJBR5B',
  );

  static FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdmtD5vJ5Hc6il-dK5_8_2MzQsQoKyVFA',
    appId: '1:608987467181:android:70a058903020f4517c6524',
    messagingSenderId: '608987467181',
    projectId: 'finalyearproject-b9f5a',
    storageBucket: 'finalyearproject-b9f5a.appspot.com',
  );

  static FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1J7cvvW4FntHHmmK0IKL8voW7HiHlSnQ',
    appId: '1:608987467181:ios:08110e43cce93cae7c6524',
    messagingSenderId: '608987467181',
    projectId: 'finalyearproject-b9f5a',
    storageBucket: 'finalyearproject-b9f5a.appspot.com',
    iosBundleId: 'com.example.finalyearApplication1',
  );

  static FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1J7cvvW4FntHHmmK0IKL8voW7HiHlSnQ',
    appId: '1:608987467181:ios:8db0dbbef23eb0a27c6524',
    messagingSenderId: '608987467181',
    projectId: 'finalyearproject-b9f5a',
    storageBucket: 'finalyearproject-b9f5a.appspot.com',
    iosBundleId: 'com.example.finalyearApplication1.RunnerTests',
  );
}
